config/routes.rb
Rails.application.routes.draw do
  get 'flats', to: 'flats#index'
  get 'flats/:id', to: 'flats#show', as: 'flat'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  before_action :set_flats

  def index
  end

  def show
    @flat = @flats.find do |flat|
      flat['id'] == params[:id].to_i
    end
  end

  private

  def set_flats
    url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
    @flats = JSON.parse(open(url).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Flats</h1>

<div class="row">
  <% @flats.each do |flat| %>
    <div class="col-4">
      <div class="card">
        <%= image_tag flat["imageUrl"], class: "card-img-top" %>
        <div class="card-body">
          <p class="card-text"><%= flat['name'] %></p>
          <%= link_to flat_path(flat['id']) do %>
            <i class="fas fa-eye"></i>
            details
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="card text-center">
  <div class="card-header">
    <%= image_tag @flat["imageUrl"], height: 300%>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @flat['name'] %></h5>
   </div>
  <div class="card-footer text-muted">
    <%= @flat["price"] %> <%= @flat["priceCurrency"] %>
  </div>
</div>

<%= link_to flats_path, class: "btn btn-primary" do %>
  <i class="fas fa-caret-square-left"></i>
  back to all flats
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoDbAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>